# Generated by Django 4.2.5 on 2023-10-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('to_do', 'To Do'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('duplicate', 'Duplicate'), ('invalid', 'Invalid'), ('wont_fix', "Won't Fix")], max_length=50),
        ),
    ]
