# Generated by Django 4.2.5 on 2023-10-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_alter_bug_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('critical', 'Critical'), ('to_do', 'To Do'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('duplicate', 'Duplicate'), ('invalid', 'Invalid'), ('wont_fix', "Won't Fix")], max_length=50),
        ),
    ]
