# Generated by Django 4.2.6 on 2023-10-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bug", "0003_alter_bug_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug",
            name="bug_type",
            field=models.CharField(
                choices=[
                    ("functional", "Functional Issue"),
                    ("performance", "Performance Issue"),
                    ("security", "Security Issue"),
                    ("usability", "Usability Issue"),
                    ("compatibility", "Compatibility Issue"),
                    ("visual", "Visual/Design Issue"),
                    ("other", "Other Issue"),
                    ("database", "Database Issue"),
                    ("network", "Network Issue"),
                    ("crash", "Application Crash"),
                    ("installation", "Installation Issue"),
                    ("documentation", "Documentation Issue"),
                    ("data_loss", "Data Loss Issue"),
                    ("accessibility", "Accessibility Issue"),
                    ("authentication", "Authentication Issue"),
                    ("workflow", "Workflow Issue"),
                ],
                max_length=225,
            ),
        ),
    ]
